HumanCellAtlas/upload-service

upload/common/logging.py, upload/lambdas/api_server/__init__.py
This PR creates all loggers from get_logger in logging module in common. Also based on forum research  at https://forum.serverless.com/t/python-lambda-logging-duplication-workaround/1585, it resets the root handlers to an empty list before adding the StreamHandler. 
I ran make test locally and the 26 tests passed. Let me know if there is something else I should be doing before creating PRs into the upload service.
=> remove root handlers and use get_logger for all calls

tests/unit/common/test_retry.py, upload/common/batch.py, upload/common/retry.py, upload/lambdas/api_server/validation_scheduler.py, upload/lambdas/checksum_daemon/checksum_daemon.py
using decorator @retry_on_aws_too_many_attempts
which wraps logic in class Retry
Note this retry functionality is similar to the library tenacity.  I tried that and their logging sucks, so wrote this simple one instead.
=> Retry attempts to communicate with AWS Batch with exponential bacoff

upload/lambdas/checksum_daemon/checksum_daemon.py
which appears to be what you get when you do a bucket-to-bucket copy of a small file.
=> checksum-daemon: also respond to ObjectCreated::Copy events

config/upload-api.yml, tests/unit/common/test_checksum.py, tests/unit/common/test_uploaded_file.py, tests/unit/docker_images/test_checksummer.py, tests/unit/lambdas/api_server/test_area.py, tests/unit/lambdas/test_checksum_daemon.py, upload/common/upload_area.py, upload/lambdas/api_server/v1/area.py
change upload create endpoint to be idempotent. related to https://app.zenhub.com/workspace/o/humancellatlas/upload-service/issues/87
=> change create on upload to be idempotent

config/upload-api.yml, terraform/envs/dev/main.tf, terraform/envs/dev/terraform.tfvars.example, terraform/envs/dev/variables.tf, terraform/envs/integration/main.tf, terraform/envs/prod/main.tf, terraform/envs/staging/main.tf, terraform/modules/upload-service/api_lambda.tf, terraform/modules/upload-service/bucket.tf, terraform/modules/upload-service/checksumming.tf, terraform/modules/upload-service/main.tf, terraform/modules/upload-service/secrets.tf, terraform/modules/upload-service/validation.tf, terraform/modules/upload-service/variables.tf, tests/functional/test_upload_service.py, tests/unit/common/test_checksum.py, tests/unit/common/test_uploaded_file.py, tests/unit/docker_images/test_checksummer.py, tests/unit/lambdas/api_server/__init__.py, tests/unit/lambdas/api_server/test_area.py, tests/unit/lambdas/api_server/test_upload_api_client.py, tests/unit/lambdas/test_checksum_daemon.py, upload/common/database.py, upload/common/upload_area.py, upload/lambdas/api_server/v1/area.py
instead of creating an IAM user for each upload area
Described in document: https://docs.google.com/document/d/1JFO75A9OR1gnCT1nYHH5p-vEaf0-TdOtOme3M3b9g3A/edit#
Paired with https://github.com/HumanCellAtlas/dcp-cli/pull/126
=> IAM-Not: get temporary aws credentials on demand

config/upload-api.yml, requirements-dev.txt, tests/unit/common/test_uploaded_file.py, tests/unit/lambdas/api_server/test_area.py, upload/lambdas/api_server/v1/area.py, upload/lambdas/api_server/validation_scheduler.py
-add hca to dev reqs
-add file size check to validation scheduler
Check file size before scheduling validation. If file is larger than 1TB should raise and exception and return a BadRequest response to the user.
Questions/Concerns
- is `test_error_not_thrown_if_file_is_appropriate_size` necessary? should I remove it?
=> US-21: [madison] add file size check to validation scheduler

terraform/modules/upload-service/bucket.tf, terraform/modules/upload-service/validation.tf, tests/unit/lambdas/api_server/test_area.py, upload/common/upload_area.py
and also returns the token expiration time too.
=> /credentials endpoint returns 1 hour tokens instead of 15 mins

terraform/envs/dev/main.tf, terraform/envs/integration/main.tf, terraform/envs/predev/main.tf, terraform/envs/prod/main.tf, terraform/envs/staging/main.tf, terraform/envs/test/main.tf
This is needed for gitlab to run terraform plan without reaching into hca-id buckets unnecessarily. This also allows us to remove upload specific policy from dcp-developer that was added in https://github.com/chanzuckerberg/dcp-infra/pull/43 to access these buckets.
=> change all locations of terraform state buckets

upload/common/checksum.py
Multipart uploads should start at 64MB+1, not 64MB.
reference: https://github.com/HumanCellAtlas/data-store/pull/1456
=> Fix multipart threshold

daemons/upload-checksum-daemon/Makefile
Need to call build in the make deploy command for the checksum daemon to allow for gitlab deployment
=> US-81: [madison] - call build in make deploy for csum lambda

scripts/retrieve_validation_statuses.py, scripts/schedule_fastq_validation.py, tests/unit/lambdas/api_server/test_area.py
Simple fix to https://app.zenhub.com/workspace/o/humancellatlas/upload-service/issues/138. No changes to docker image needed on further inspection since they call back to upload api with event_id (validation or checksum db unique id) instead of filename
=> fix for hash in filename in scripts

daemons/upload-checksum-daemon/Makefile, database/env.py, terraform/envs/dev/Makefile, terraform/envs/dev/main.tf, terraform/envs/dev/terraform.tfvars.example, terraform/envs/dev/variables.tf, terraform/envs/integration/main.tf, terraform/envs/predev/main.tf, terraform/envs/prod/main.tf, terraform/envs/staging/main.tf, terraform/envs/test/main.tf, terraform/envs/test/terraform.tfvars.example, terraform/envs/test/variables.tf, terraform/modules/database/database.tf, terraform/modules/database/outputs.tf, terraform/modules/database/pgbouncer.tf, terraform/modules/database/secrets.tf, terraform/modules/database/subnet.tf, terraform/modules/upload-service/api_lambda.tf, terraform/modules/upload-service/checksumming_batch.tf, terraform/modules/upload-service/checksumming_lambda.tf, terraform/modules/upload-service/main.tf, terraform/modules/upload-service/secrets.tf, terraform/modules/upload-service/validation.tf, terraform/modules/upload-service/variables.tf, terraform/modules/vpc/main.tf, terraform/modules/vpc/vpc.tf, upload/common/database.py, upload/common/database_orm.py, upload/common/upload_config.py
You can now install new deployments of the upload service, without excessive messing about.
This document describes the process:
https://github.com/HumanCellAtlas/upload-service/wiki/Setting-up-a-new-Deployment-of-the-Upload-Service
=> Make upload service installable

Makefile, config/upload-api.yml, daemons/upload-checksum-daemon/Makefile
- move version endpoint into swagger all section
- remove call to daemon clobber (there is no make command/nothing to clobber)
=> Update swagger tag

config/environment, terraform/modules/upload-service/validation.tf, tests/unit/common/test_uploaded_file.py, upload/common/batch.py, upload/lambdas/api_server/validation_scheduler.py
- changes validation maxVCPUs to 512 to account for expected burst load
- changes validation job definition to allocate approximately 2gb of ram
- fix to allow for hashes in url in validation scheduler
=> fixes for validation

config/upload-api.yml, tests/unit/lambdas/api_server/test_area.py, upload/common/upload_area.py, upload/lambdas/api_server/v1/area.py
* Developers need to be able to check the status of all files in an upload area
* query db for status (checksum and validation) of all files in a given upload area
* return a dict of possible statuses and file count
* tested sql query on dev db
* unit tests for endpoint
=> add endpoints to get status (checksum and validation) of all files in an upload area

tests/unit/lambdas/test_checksum_daemon.py, upload/lambdas/checksum_daemon/checksum_daemon.py
The api was checksumming the metadata file from store_file call when at the same time the checksum daemon was triggered by object put to s3. The checksum daemon then just checked to see if there were any newer checksum events rather than confirming that the event was complete as well. It notified ingest which then allowed for submission and deletion of files before the first process could successfully put checksums on the file
=> don't notify ingest if file is still checksumming

daemons/upload-checksum-daemon/Makefile, terraform/modules/upload-service/checksumming_lambda.tf
Need to add the deployment stage to the bucket name (instead of as part of the key inside of the bucket) to allow for prod access
=> namespace csum lambda deployment bucket

docker-images/base-alpine-python36/harness.py, tests/unit/common/test_uploaded_file.py, upload/lambdas/api_server/validation_scheduler.py
`validation_id` is now always the self-generated UUID4.
When communication with external entities (passing `VALIDATION_ID`
environment variable to validators, reporting results to Ingest),
always use generated `validation_id`.
=> Clean up usage of `validation_id` vs. `job_id`

terraform/modules/upload-service/api_lambda.tf, terraform/modules/upload-service/checksumming_lambda.tf
Batch does not support resource paths. All batch permissions need resource path of `*`
Message in iam console: The actions in your policy do not support resource-level permissions and require you to choose All resources
=> batch resource path now needs to be asterisk

upload/common/checksum.py, upload/common/ingest_notifier.py, upload/common/logging.py, upload/docker_images/checksummer/checksummer.py, upload/docker_images/validator/validator_harness.py, upload/lambdas/api_server/__init__.py, upload/lambdas/checksum_daemon/checksum_daemon.py
This was a nice idea but never took off, and just makes the log entries too noisy.
=> remove correlation ID from log entries

tests/unit/common/test_database.py, tests/unit/lambdas/api_server/test_area.py, tests/unit/lambdas/api_server/test_health.py, tests/unit/lambdas/api_server/test_upload_api_client.py, tests/unit/lambdas/api_server/test_validation_api.py, tests/unit/lambdas/test_batch_watcher.py, tests/unit/lambdas/test_checksum_daemon.py, tests/unit/lambdas/test_health_check.py, upload/common/checksum_event.py, upload/common/database.py, upload/common/database_orm.py, upload/common/ingest_notifier.py, upload/common/upload_area.py, upload/common/uploaded_file.py, upload/common/validation_event.py, upload/lambdas/batch_watcher/batch_watcher.py, upload/lambdas/checksum_daemon/checksum_daemon.py, upload/lambdas/health_check/health_check.py
Having the database initialization done in an __init__ method instead
of at file parse time makes it easier to change configuration for
testing purposes.
However, calling Metadata() takes about 7 seconds, so we don't want
to do it a lot.  For this reason we store the engine and record_type_table_map
in class variables.
=> Refactor: wrap common/database code in a class: UploadDB

config/upload-api.yml, terraform/modules/upload-service/secrets.tf, tests/unit/__init__.py, tests/unit/common/test_database.py, tests/unit/lambdas/api_server/test_area.py, upload/common/upload_area.py, upload/lambdas/api_server/v1/area.py
This PR is relevant to ticket https://github.com/HumanCellAtlas/upload-service/issues/227. It accomplishes the first bullet point: `Post /area/file endpoint in upload api that adds file payload to pre-csum sqs`. Steps 2 and 3 remain and are dependent on this api change being promoted through all environments.
=> add post /area/file endpoint that adds file payload to pre checksum sqs

terraform/modules/upload-service/checksumming_lambda.tf
Cloudwatch insights suggest that we are routinely bumping into the 960mb limit in staging and production. This PR bumps it up to 1500mb. I will reanalyze the memory consumption after a few months.
=> Increase csum memory

terraform/modules/upload-service/bucket.tf
This is related to point # 3 in ticket https://github.com/HumanCellAtlas/upload-service/issues/227: `Remove link between s3 and sqs`. Sqs will now be fed directly via calls to the upload api from the hca cli. This is not to be merged in until the api change (https://github.com/HumanCellAtlas/upload-service/pull/243) has been promoted through all environments and changes to hca cli have been made with new version cut.
=> remove link between s3 and sqs

tests/unit/__init__.py, tests/unit/common/test_database.py, tests/unit/common/test_upload_area.py, tests/unit/lambdas/api_server/test_area.py, upload/common/database_orm.py, upload/common/upload_area.py, uploadctl/cleanup/__init__.py, uploadctl/cleanup/upload_cleaner.py, uploadctl/cli.py, uploadctl/test/batch.py
New command: `uploadctl cleanup` removes DB records for which there are no S3 objects.
Cleanup method order in `UploadedFile`
Test cleanup: create a separate test for `UploadArea`
Cleanup usage of `UploadConfig` in `UploadArea`
Fix `UploadException` usage
=> Many kinds of cleanup

Makefile, database/versions/217fe1d22e4e_file_s3_etag_not_null.py, tests/unit/lambdas/test_checksum_daemon.py, upload/common/checksum.py
Commit b56b902c "Record s3_etag in File DB records" has been propagated all the way to production.
`uploadctl cleanup files` has been run in all environments to back-populate all rows with an s3_etag.
There are now no rows with a NULL s3_etag so we can now make that column NOT NULL.
=>  db: make file.s3_etag NOT NULL

tests/unit/docker_images/test_validator_harness.py, upload/common/dss_checksums.py, upload/common/ingest_notifier.py, upload/common/upload_area.py, upload/common/validation_scheduler.py, upload/docker_images/validator/validator_harness.py
In all Tenacity retries, updating the signature so that the original error is thrown using the flag reraise=True instead of throwing a RetryError which essentially swallows the original error. Updated the necessary tests.
=> Reraise original errors where tenacity retries are used instead of throwing a tenacity retry error

tests/__init__.py, tests/functional/test_upload_service.py, upload/common/uploaded_file.py
This is related to #304. This follows https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel via using write than read in order to avoid eventual consistency issues. This PR also adds in a functional test for put_file via the api.
=> use write/read for s3 consistency on s3 put and add functional test for put_file via api

terraform/envs/dev/main.tf, terraform/envs/dev/terraform.tfvars.example, terraform/envs/dev/variables.tf, terraform/envs/integration/main.tf, terraform/envs/parth/main.tf, terraform/envs/predev/main.tf, terraform/envs/prod/main.tf, terraform/envs/staging/main.tf, terraform/envs/testing/main.tf, terraform/modules/database/database.tf, terraform/modules/database/variables.tf, terraform/modules/upload-service/main.tf, terraform/modules/upload-service/variables.tf
Values set for current environment in updated tfvars files:
Dev: "sat:09:08-sat:09:38"
Integration: "sat:09:08-sat:09:38"
Staging : "wed:15:00-sat:15:30" (8-8:30am EST for deployments)
Prod: "tue:15:00-sat:15:30" (8-8:30am EST for deployments)
=> use dynamic maintenance window for rds

tests/unit/common/test_uploaded_file.py, tests/unit/lambdas/test_checksum_daemon.py
Because we have a shared test database, tests running simultaneously
can stomp all over each other.  Randomize filenames used in tests and
make queries filter on the filenames.
=> Fix test interaction problems

terraform/modules/upload-service/batch_watcher.tf, terraform/modules/upload-service/health_check_lambda.tf
tested by removing dev from std env list and running make apply in dev env
=> Don't trigger monitoring daemons for non standard environments

amis/README.md, terraform/envs/dev/main.tf, terraform/envs/dev/terraform.tfvars.example, terraform/envs/dev/variables.tf, terraform/envs/integration/main.tf, terraform/envs/prod/main.tf, terraform/envs/sam/main.tf, terraform/envs/staging/main.tf, terraform/envs/test/main.tf, terraform/envs/test/terraform.tfvars.example, terraform/envs/test/variables.tf, terraform/modules/upload-service/checksumming_batch.tf, terraform/modules/upload-service/validation.tf, terraform/modules/upload-service/variables.tf
I have created a new AMI for validation, `ami-0939b827b1bf145c9` a.k.a. _ecos-with-data-vol-m5-v2_.  I updated and expanded the instructions on how to create it.  This AMI is for M5 instances (instead of M4).
I've also updated the checksumming cluster to m5 at the same time.
As you deploy this code to each environment, you need to change `terraform.tfvars`:
```
validation_cluster_ami_id = "ami-0939b827b1bf145c9"
validation_cluster_instance_type = "m5"
csum_cluster_instance_type = "m5"
```
To apply these terraform changes, you will need to delete the Batch job queues first
as Terraform seems to be dumb about the relationship between queues and clusters:
```
tf destroy --target=module.upload-service.aws_batch_job_queue.validation_job_q
tf destroy …
```
=> New Validation AMI, use M5 instances in Batch

config/upload-api.yml, tests/unit/lambdas/api_server/test_area.py, upload/lambdas/api_server/v1/area.py
Removing endpoint GET /v1/area/{upload_area_uuid}.
This is and unused endpoint.
Listing files is done another way as it was discovered that this
strategy was not scalable.
Listing upload areas is done by listing the S3 bucket directly, then
calling the upload API PUT /v1/area/{upload_area_uuid}/files_info to
get the upload-specific info about the files.
**IMPORTANT: Next time we promote to Integration, PLEASE BUMP THE MAJOR VERSION NUMBER.**
=> Remove "list upload area" REST API endpoint

chalice/build_deploy_config.sh, scripts/get_api_id, terraform/envs/dev/main.tf, terraform/envs/dev/terraform.tfvars.example, terraform/envs/dev/variables.tf, terraform/envs/integration/main.tf, terraform/envs/prod/main.tf, terraform/envs/sam/main.tf, terraform/envs/staging/main.tf, terraform/modules/upload-service/dns.tf, terraform/modules/upload-service/variables.tf
* As an operator of the upload service
* I want a subdomain created for the upload API as part of deployment
* so that I don't have to create it by hand
This PR retrieves the zone ID for the parent DNS domain and the certificate for that domain and creates a Route53 A Record alias tied to an API Gateway domain name.
This is confirmed to work for `dev`, but the `parent_zone_domain_name` variable has not yet been added to `terraform.tfvars` for the `integration`, `staging`, and `prod` deployment environments.
As the code changes propagate through the deployment stages, operators will have to take the following steps to roll out the changes:
1. The build will fail since the following resources have not yet been imported in the state file.
1. `aws_api_gateway_domain_name.upload`
1. …
=> Configure API DNS record set in terraform

requirements-dev.txt, tests/__init__.py, tests/functional/test_upload_service.py, tests/functional/waitfor.py
instead of calling the REST API directly.
Try to format test output to be more sectioned and readable.
=> Rewrite functional tests to use the hca.upload library (#355)
