HumanCellAtlas/upload-service

- terraform/envs/dev/Makefile
- terraform/envs/dev/main.tf
- terraform/envs/integration/Makefile
- terraform/envs/integration/main.tf
- terraform/envs/prod/Makefile
- terraform/envs/prod/main.tf
- terraform/envs/staging/Makefile
- terraform/envs/staging/main.tf
Use same state bucket as dcp-infra (in hca-id acct), for both non-prod & prod
Switch to Terraform 0.11.7
> Terraform config update

- tests/unit/lambdas/test_checksum_daemon.py
- upload/common/checksum.py
- upload/common/checksum_event.py
- upload/lambdas/checksum_daemon/checksum_daemon.py
Resurrect this functionality to relieve pressure on Batch and reduce
costs at scale.
> Resurrect in-lambda checksumming

- terraform/envs/test/main.tf
- terraform/envs/test/terraform.tfvars.example
- terraform/envs/test/variables.tf
- terraform/modules/database/outputs.tf
- terraform/modules/database/pgbouncer.tf
- terraform/modules/database/variables.tf
- terraform/modules/upload-service/main.tf
- upload/common/database.py
pgbouncer branch got in a weird state so created a new PR.
This PR is related to repo https://github.com/HumanCellAtlas/docker-pgbouncer which builds relevant docker image in quay that is deployed in ECS. ECS made the most sense for a single container, single service setup.
> Pgbouncer clean

- database/versions/2c6910ed8cf6_add_indices.py
related to https://app.zenhub.com/workspace/o/humancellatlas/upload-service/issues/70
> db indices

- terraform/modules/upload-service/api_lambda.tf
- terraform/modules/upload-service/checksumming.tf
- terraform/modules/upload-service/validation.tf
Also add settings for Batch instance tags, but left them commented out
as they do not appear to work.  Terraform attempts to set them on every
apply.
> Fix some hardcoded values in Terraform

- config/upload-api.yml
- docker-images/base-alpine-python36/harness.py
- scripts/create_upload_area.py
- scripts/retrieve_validation_statuses.py
- scripts/schedule_fastq_validation.py
- tests/unit/lambdas/api_server/test_area.py
- upload/common/database.py
- upload/common/uploaded_file.py
- upload/lambdas/api_server/v1/area.py
- validation event status check api endpoint that returns status and results (if any)
- scripts to schedule and retrieve validation events
> Validation event api

- terraform/modules/upload-service/checksumming_batch.tf
- terraform/modules/upload-service/fetch_batch_vcpus.py
- terraform/modules/upload-service/validation.tf
This PR uses external data source to fetch current status of desired vcpus of checksumming and validation compute environments while running terraform
> fetch current desired vcpus

- .gitlab-ci.yml
- daemons/upload-checksum-daemon/Makefile
> US-81-deployment: [madison] - update for deployment pipeline

- config/upload-api.yml
> Update api yml

- upload/common/uploaded_file.py
Fixes https://app.zenhub.com/workspace/o/humancellatlas/upload-service/issues/174
> fix race condition

- config/upload-api.yml
- tests/unit/lambdas/api_server/test_area.py
- upload/lambdas/api_server/v1/area.py
Ingest needs an endpoint to check if an upload area exists during exporting process.
> add head to upload area

- daemons/health-check-daemon/Makefile
- daemons/upload-checksum-daemon/Makefile
- terraform/modules/upload-service/bucket.tf
- terraform/modules/upload-service/checksumming_lambda.tf
- terraform/modules/upload-service/health_check_lambda.tf
- put all lambda daemons into the same s3 bucket
- use lambda name as bucket key
> US-191: [madison] merge lambda daemon deployment buckets

- requirements-dev.txt
- requirements.txt
Turns out tests run cleanly with no changes required.
> Upgrade boto3, moto (#222)

- docker-images/base-alpine-python36/Makefile
- docker-images/base-alpine-python36/harness.py
- docker-images/validator-example/Makefile
- tests/unit/docker_images/test_validator_harness.py
- upload/docker_images/validator/validator_harness.py
Move most of class ValidatorHarness up under upload/
to make it testable.
> Write tests for validator harness

- requirements.txt
- tests/unit/docker_images/test_validator_harness.py
- upload/docker_images/validator/validator_harness.py
When file is not present on filesystem after Bucket().download_file()
> ValidatorHarness: retry _stage_file_to_be_validated

- daemons/health-check-daemon/requirements.txt
- daemons/upload-checksum-daemon/requirements.txt
- upload/common/checksum.py
- upload/common/uploaded_file.py
- upload/lambdas/checksum_daemon/checksum_daemon.py
> catch missing checksums and retry on put tags to s3 object

- terraform/modules/upload-service/batch_watcher.tf
- tests/unit/lambdas/test_batch_watcher.py
- upload/lambdas/batch_watcher/batch_watcher.py
PR for #232
batch watcher fixes including retry on boto3 batch describe_job and policy on batch watcher to invoke checksum daemon
> batch watcher fixes

- config/iam-policy-templates/upload-api-lambda.json
- terraform/modules/upload-service/api_lambda.tf
- terraform/modules/upload-service/secrets.tf
- tests/unit/__init__.py
- tests/unit/common/test_database.py
- upload/common/upload_area.py
fix sqs url in secrets and permission for api to add to sqs and upload sqs variable name
> small fixes to get api => sqs to work

- database/versions/1c7493144cbf_on_delete_cascade.py
which makes removing things from the DB much easier
> Make all database fk constraints ON DELETE CASCADE

- tests/unit/lambdas/test_health_check.py
- upload/lambdas/health_check/health_check.py
- more informative/less crufty slack messages from health check bot
- if no new messages in deadletter queue return 'GOOD' instead of message (even if there are old messages in deadletter queue)
- if no stale_checksumming_areas, stale_validating_areas, scheduled_checksum_areas, scheduled_validation_areas, failed_checksum_count, failed_validation_count return 'GOOD' instead of message (even if there are undeleted upload areas)
- if no lambda errors return 'GOOD' instead of message
- if any of the above are not 'GOOD' mark bot post in red to draw attention to it
- if the status is 'GOOD' for all of the above post "It's 6 o'clock somewhere and all is well" and mark bot post green
- update unit tests to include no error situations
> reduce unnecessary information posted by health check bot

- Makefile
- config/upload-api.yml
- database/versions/5ea5c9b56a3d_upload_area_integer_pk.py
- tests/unit/common/test_database.py
- tests/unit/common/test_upload_area.py
- tests/unit/common/test_uploaded_file.py
- tests/unit/lambdas/api_server/test_area.py
- tests/unit/lambdas/api_server/test_checksum_api.py
- tests/unit/lambdas/api_server/test_upload_api_client.py
- tests/unit/lambdas/test_checksum_daemon.py
- upload/common/database.py
- upload/common/database_orm.py
- upload/common/upload_api_client.py
- upload/common/upload_area.py
- upload/common/uploaded_file.py
- upload/lambdas/api_server/v1/area.py
rename the old 'id' column to 'uuid'
> Make UploadArea database id an integer sequence

- terraform/envs/dev/main.tf
- terraform/envs/dev/terraform.tfvars.example
- terraform/envs/dev/variables.tf
- terraform/envs/integration/main.tf
- terraform/envs/predev/main.tf
- terraform/envs/prod/main.tf
- terraform/envs/staging/main.tf
- terraform/envs/testing/main.tf
- terraform/modules/upload-service/bucket.tf
- terraform/modules/upload-service/secrets.tf
- terraform/modules/upload-service/variables.tf
- tests/unit/__init__.py
- upload/common/upload_area.py
These are the policies required for ticket #231 and related to https://github.com/HumanCellAtlas/dcp-cli/pull/217/files
> policies for upload from cloud url

- requirements-dev.txt
- terraform/modules/upload-service/bucket.tf
- tests/functional/test_upload_service.py
- upgrade hca cli to v4.6.0
- move away from aws cp
- remove bucket to sqs notification post file upload
> upgrade hca cli to v4.6.0

- config/database.ini
- terraform/envs/parth/Makefile
- terraform/envs/parth/main.tf
- terraform/envs/parth/terraform.tfvars.example
- terraform/envs/parth/variables.tf
created parth upload environment
> create parth upload environment

- chalice/app.py
- daemons/area-deletion-daemon/app.py
- daemons/health-check-daemon/app.py
- daemons/upload-checksum-daemon/app.py
- daemons/validation-scheduler-daemon/app.py
- upload/common/checksum_event.py
- upload/common/dss_checksums.py
- upload/common/ingest_notifier.py
- upload/common/logging.py
- upload/common/upload_api_client.py
- upload/common/upload_area.py
- upload/common/validation_event.py
- upload/common/validation_scheduler.py
- upload/docker_images/checksummer/checksummer.py
- upload/docker_images/validator/validator_harness.py
- upload/lambdas/api_server/__init__.py
- upload/lambdas/api_server/v1/area.py
- upload/lambdas/batch_watcher/batch_watcher.py
- upload/lambdas/checksum_daemon/checksum_daemon.py
- upload/lambdas/health_check/health_check.py
Reverts HumanCellAtlas/upload-service#289
> Revert "Update logger.py to create only one root logger that emits messages to de-dup log messages."

- tests/__init__.py
- tests/fixtures/small_invalid_file
- tests/functional/test_upload_service.py
- Added a new file that will fail validation and a new test that accordingly checks the validation result to make sure the exit code and the output designate the file as invalid.
- Updated existing functional tests to check that the validation was successful.
- Renamed some tests to follow the patter _test_testParameters_expectedResult.
- Reordered the functions in the file such that tests come first, followed by high level executive commands, followed by verification methods, followed by miscellaneous helper functions.
- Renamed functions such that high level executive commands are prepended with _execute, verification methods are prepended with _verify, and getter functions are prepended with _get.
- Added timing to tests.
> Added a new functional test for a file that failed validation

- config/upload-api.yml
- tests/unit/lambdas/api_server/test_health.py
- upload/lambdas/api_server/health_check.py
- upload/lambdas/api_server/v1/health_check.py
This is for ticket #302. This updates the health check to not be nested within /v1 and checks health of db
> update health check to not be nested within /v1 and check health of db

- terraform/envs/dev/Makefile
- terraform/envs/integration/Makefile
- terraform/envs/prod/Makefile
- terraform/envs/sam/Makefile
- terraform/envs/staging/Makefile
- terraform/envs/test/Makefile
- terraform/modules/upload-service/batch_shared.tf
Fixes https://github.com/HumanCellAtlas/upload-service/issues/361
> Namespace the roles we can and remove them from state import/rm step

- terraform/envs/dev/terraform.tfvars.example
- terraform/envs/dev/variables.tf
- terraform/envs/sam/main.tf
- terraform/modules/upload-service/dns.tf
- terraform/modules/upload-service/variables.tf
instead of searching for it each time which takes a really long time.
> Put API Gateway ID in terraform.tfvars

- uploadctl/runlevel/lambda_mgr.py
uploadctl: add validation-scheduler and area-deletion lambdas to Big Red Button command (`uploadctl runlevel stop/start/status`)
> Update Big Red Button (#332)
